name: Docker CI Pipeline

on:
  push:
    branches:
      - main  # Runs when code is pushed to main
  pull_request:
    branches:
      - main  # Runs on PRs to main

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment (for testing)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # Step 3: Install dependencies (for testing)
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      # Step 4: Run tests (if you have them)
      - name: Run Tests
        run: |
          pytest || echo "Tests failed!"

      # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # Step 6: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/llm-inference-image ./homeworks/one

      # Step 7: Push the image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/llm-inference-image
